env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    #4
task:
    name: omaralcoptan
    timeout_in: 120m
    container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32g
      commands:
      - sudo apt-get install gpg
      - rm -rf ~/.repoconfig
      - sudo apt-get upgrade
    download_ccache_background_script: # To download ccache in background
      - bash download_ccache # Ccache download script
    sync_script: # To sync rom source and dt, vt, kernel etc.
      - bash sync # Sync script
    build_script: # To build rom
      - bash build # Rom build script
    upload_ccache_script: # Upload ccache to cloud foreground
      - bash upload_ccache # Ccache uploading script
