#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom


##some of my work
git config --global user.name "OmarAlCoptan"
git config --global user.email "omarcoptan9@gmail.com"

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u https://github.com/PixelExperience/manifest -b twelve -g default,-mips,-darwin,-notdefault

# Local manifest
git clone https://github.com/OmarAlCoptan/local_manifest.git --depth 1 -b pe .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8


